### ISSUE TITLE
Interpolate Demo is Broken

### ISSUE THREAD

**Issue by StephenAshmore** [mikegashler/waffles#13]
### Runtime Issue
The Interpolate Demo seems to be broken. This isn't a simple compiler issue ( though there is one, I'll get to that in a second ), but rather an actual runtime issue. In the interpolate demo, using 1-NN, 4-nn, or neural network ( and presumably the others as well ) a GVec Debug Assert failed will be encountered at line 78 in GVec. This is an out-of-bounds issue. Somewhere in Interpolate Demo the code requests a GVec position that is out of bounds. 

### Compiler Issue
There is also a compiler issue that is easy to fix. The transduce method call at line 228 in main.cpp returns a std::unique_ptr, which cannot simply be stored into a GMatrix. The fix is as follows:
Change line 228 to: std::unique_ptr<GMatrix> pLabels = pModel->transduce(*m_pTrainingFeatures, *m_pTrainingLabels, dataUnlabeled);
And comment out line 229 ( Holder<GMatrix> hLabels(pLabels); ), because a holder does not currently support unique_ptrs.

**Comment by mikegashler** [comment]
Thanks. Fixed.
