### ISSUE TITLE
Unsigned Integers and Signed Integers

### ISSUE THREAD

**Issue by StephenAshmore** [mikegashler/waffles#18]
We have this issue semi-frequently when working across Mac and Linux. Due to the compiler difference #14, comparing unsigned integers and signed integers will compile just fine on Mac, but give compiler errors on Linux. Windows is untested. 

Here is an example in the current commit from file Glayer.cpp at line 1779:
```
size_t i = index(x, y, z);
if(i == -1)
	return 0.0;
```
The index method is returning an unsigned integer (size_t), but when an index is not able to be found it returns -1. We really should be comparing i to string::npos ( or some other npos ).

While fixing these compiler errors is trivial, perhaps we should enforce the compiler flags, or remove the strictness. Something else would be to set up an automatic build system that builds and tests on the three major platforms ( Windows, Linux, and Mac ) whenever a commit comes through. That would allow contributors to easily push in code and see that it fails on some other OS.

**Comment by thelukester92** [comment]
That's what makes me think that it would be nice to use g++-5 on Mac to enforce (more closely) cross-platform compatibility. For this particular issue, I think an npos would be better. I'll work on a  fix.

**Comment by thelukester92** [comment]
Pushed a fix: a static size_t npos for GLayerConvolutional2D.
