### ISSUE TITLE
Inconsistencies

### ISSUE THREAD

**Issue by StephenAshmore** [mikegashler/waffles#23]
It has been noted that there are some inconsistencies with syntax in waffles. For example, the GMatrix class has a setAll method, but then has methods called fillUniform etc. GVec also has a fill method. This is a very low priority issue, and should be considered a quality of life fix. I don't want to go through pushing a bunch of method name changes without getting some feedback first.

**Comment by thelukester92** [comment]
I second this; perhaps leave the old method names in as aliases (just call the actual method) and mark the old one as deprecated?

**Comment by thelukester92** [comment]
I second this; perhaps leave the old method names in as aliases (just call the actual method) and mark the old one as deprecated?

**Comment by mikegashler** [comment]
"setAll" exists because I wrote it a long time ago. "fill" is more
consistent with STL containers, so I think we should push in that
direction. Since we are still small, I think it is better to be agile
than to worry about maintaining backward compatibility, so I propose we
just fix it and don't worry too much about whose code breaks.

**Comment by StephenAshmore** [comment]
We should be able to fix these up after @thelukester92 's big merge as part of #26. I'll fix up the inconsistencies in names that aren't already fixed by @thelukester92, and then we should be able to mark waffles 1.1 as done.

**Comment by StephenAshmore** [comment]
Fixed the fill, and a couple of other things. If there are other inconsistencies that you find, please let me know and I can fix them up. Closing this issue for now.
