### ISSUE TITLE
TrainIncremental does not throw exception

### ISSUE THREAD

**Issue by StephenAshmore** [mikegashler/waffles#24]
In the GNeuralNet class, the trainIncremental method does not throw an exception if the beginIncrementalLearning method has not been called. This leads to some bizarre behavior for new users of Waffles ( a segmentation fault when they call trainIncremental ).

**Comment by StephenAshmore** [comment]
Pushed a fix for this. However, this fix causes a per training pattern if statement, which probably will slow down training. Calling @thelukester92 @mikegashler for comments, before this is closed.

The fix here is just an if statement inside of trainIncremental.

**Comment by thelukester92** [comment]
Should use GAssert instead of an exception so that it only slows down debugging but not optimized training.

**Comment by StephenAshmore** [comment]
I agree, forgot this existed when I pushed that fix. I will change and push in a moment.
Perhaps we should make a note that beginners should compile in debug mode until they work out the kinks of their programs ( which should be obvious, but people are involved and we don't always notice the obvious ).

**Comment by StephenAshmore** [comment]
This is now fixed, using the optimized GAssert version.

**Comment by StephenAshmore** [comment]
This should also be in place for trainIncrementalBatch and the @thelukester92 upcoming RMSProp versions. Reopened, but will be closed shortly.

**Comment by thelukester92** [comment]
Done.
