### ISSUE TITLE
Compiling on Windows using MSVC 2015 [execinfo.h missing]

### ISSUE THREAD

**Issue by aveshd** [mikegashler/waffles#28]
Hi,

Very impressive work. I tried to follow the instruction for compiling on windows using MSVC++ 2015 community version. Here are the key errors I got:

===============================================
Severity	Code	Description	Project	File	Line	Suppression State
Error	C1083	Cannot open include file: 'execinfo.h': No such file or directory	GClasses	C:\Users\user_name\Downloads\waffles-master\src\GClasses\GError.cpp	31	
Error	C1083	Cannot open source file: 'sha1.cpp': No such file or directory	GClasses	C:\Users\user_name\Downloads\waffles-master\src\GClasses\c1xx	1	
Error	LNK1181	cannot open input file 'GClasses.lib'	waffles_learn	C:\Users\user_name\Downloads\waffles-master\src\learn\LINK	1	
Error	LNK1181	cannot open input file 'C:\Users\user_name\Downloads\waffles-master\lib\GClasses.lib'	waffles_wizard	C:\Users\user_name\Downloads\waffles-master\src\wizard\LINK	1	
Error	LNK1181	cannot open input file 'C:\Users\user_name\Downloads\waffles-master\lib\GClasses.lib'	waffles_cluster	C:\Users\user_name\Downloads\waffles-master\src\cluster\LINK	1	
Error	LNK1181	cannot open input file 'GClasses.lib'	waffles_sparse	C:\Users\user_name\Downloads\waffles-master\src\sparse\LINK	1	
Error	LNK1181	cannot open input file 'GClasses.lib'	waffles_recommend	C:\Users\user_name\Downloads\waffles-master\src\recommend\LINK	1	
Error	LNK1181	cannot open input file 'GClasses.lib'	test	C:\Users\user_name\Downloads\waffles-master\src\test\LINK	1	
Error	LNK1181	cannot open input file 'GClasses.lib'	waffles_plot	C:\Users\user_name\Downloads\waffles-master\src\plot\LINK	1	
Error	LNK1181	cannot open input file 'C:\Users\user_name\Downloads\waffles-master\lib\GClasses.lib'	waffles_transform	C:\Users\user_name\Downloads\waffles-master\src\transform\LINK	1	
Error	LNK1181	cannot open input file 'GClasses.lib'	waffles_audio	C:\Users\user_name\Downloads\waffles-master\src\audio\LINK	1	
Error	LNK1181	cannot open input file 'C:\Users\user_name\Downloads\waffles-master\lib\GClasses.lib'	waffles_dimred	C:\Users\user_name\Downloads\waffles-master\src\dimred\LINK	1	
===============================================

Please help. 

I would prefer to use cmake on windows to build the library, if you have instruction for doing that I would like to follow that.

regards,
Avi

**Comment by mikegashler** [comment]
I just pushed a fix. I only tested on MSVC++ 2013 Express Edition, but I believe it will work on your version. Unfortunately, I have never tried using cmake on Windows.

**Comment by aveshd** [comment]
Thank you, It worked !!!!!
