### ISSUE TITLE
Error when importing CSV in waffles_transform

### ISSUE THREAD

**Issue by m-shawkey** [mikegashler/waffles#3]
when I try running "waffles_transform.exe  import data.csv", a "Mismatching size" error is encountered.

**Comment by mikegashler** [comment]
Thanks! Can you provide repro steps?

**Comment by m-shawkey** [comment]
I downloaded the code and built it using VS2013.
when I run "waffles_transform.exe import data.csv > data.arff". I get "Mismatching size" error message.
here are the contents of data.csv 

3.3, 1.2, 3.5, 0
2.1, 5.6, 3.6, 1
2.0, 0.4, 0.7, 0

**Comment by mikegashler** [comment]
Fixed.
