### ISSUE TITLE
Compile problem on macOS

### ISSUE THREAD

**Issue by codespear** [mikegashler/waffles#35]
I get a few errors like these while compiling (`make install`) on macOS Sierra, clang 800.0.42.1.

    In file included from GActivation.cpp:27:
    ./GNeuralNet.h:228:7: error: 'step' overrides a member function but is not marked 'override' [-Werror,-Winconsistent-missing-override] 
    void step(double learningRate, const GVec &gradient);`

**Comment by mikegashler** [comment]
My testing on macOS has been somewhat sporadic (because I don't have a Mac). I think I should remove "-Werror" from the compiler flags when the Makefile detects that it is using clang, so small issues like this don't create compile errors. I did that. Does this make the problem go away for you?

**Comment by codespear** [comment]
I am new to the Mac, but maybe I can help you out a bit. 
The -Werror flag did not work.  The warnings are few enough to fix.  Should I fix it and create a pull request?
