### ISSUE TITLE
Improve GFilter::innerLearner() documentation

### ISSUE THREAD

**Issue by albertouri** [mikegashler/waffles#41]
This is something not explained in the documentation and not obvious (at least for me).

We have this method `GSupervisedLearner* GFilter::innerLearner()` that returns the innerLearner then I can have for example a GNeuralNet inside like this:
```c++
GNeuralNetLearner *learner = new GNeuralNetLearner();
learner->nn().add(new GBlockLinear(2));
learner->nn().add(new GBlockLogistic());
GAutoFilter *pModel = new GAutoFilter(learner);
```
Now to access to the NN we can do it like this:
```c++
GSupervisedLearner* learner = pModel->innerLearner();
GNeuralNetLearner* nnLearner = dynamic_cast<GNeuralNetLearner*>(learner);
```
No problems here, the party begins once we train the GAutoFilter:
```c++
pModel->train(features, labels);
GSupervisedLearner* learner = pModel->innerLearner();
GNeuralNetLearner* nnLearner = dynamic_cast<GNeuralNetLearner*>(learner);
```
Now `nnLearner` will be a `nullptr`!!! Why? Well, it turns out that `GNeuralNet` needs the data to be normalized. To do so it concatenates different `GFilter` (one for features and another for the labels) and if you remember, each GFilter has an innerLerner. So, to access the NN after training we need to do this:
```c++
pModel->train(features, labels);
GSupervisedLearner* learner = pModel->innerLearner();
GLabelFilter* learner2 = dynamic_cast<GLabelFilter*>(learner);
GFeatureFilter* learner3 = dynamic_cast<GFeatureFilter*>(learner2->innerLearner());
GNeuralNetLearner* nnLearner = dynamic_cast<GNeuralNetLearner*>(learner3->innerLearner());
```

I think this should be warned in the documentation. And it would be great to add a new method that returns "the most inner learner"

**Comment by mikegashler** [comment]
Good point. The GFilter::discardIntermediateFilters method does something rather similar. It finds the "most inner learner" and deletes everything else. So, to do what you want, all we need to do is make a version of this method that skips the "delete everything else" step.

I recently added the GDataPreprocessor class, which provides approximately the same functionality as GAutoFilter. (Currently the only example for using GDataPreprocessor is in the MNIST example in the neural net documentation.) I think processing the data before learning begins is both more efficient and generally more intuitive than processing it on the fly. So, my plan has been to phase out GAutoFilter and phase in GDataPreprocessor, but I haven't yet found the time to really do it.
