### ISSUE TITLE
KNN : Cannot use SparseMetrics

### ISSUE THREAD

**Issue by skn123** [mikegashler/waffles#7]
I would like to use a set of feature stored in GMatrix and a sparse distance metrix (e.g., Cosine). However, there is no API to do this. Can this be fixed in the code?

**Comment by mikegashler** [comment]
The GSparseSimilarity class (which is the parent class of all my sparse metrics) currently contains 2 abstract methods named "similarity". One of them compares a sparse vector with a sparse vector, and the other one compares a sparse vector with a GVec (fully-specified vector). If I understand your request correctly, you would like a third overload that compares two GVec instances. This would allow you to use any of the sparse similarity metrics to compare two rows from a GMatrix. Do I understand correctly?

**Comment by skn123** [comment]
Yes.. Distances  can and should be defined for any type of vectors; sparse or dense.

**Comment by mikegashler** [comment]
Good idea! Done.

**Comment by skn123** [comment]
I am still getting this error
RuntimeError: This method is not compatible with sparse similarity metrics. You should either use trainSparse instead, or use a dense dissimilarity metric. I am trying to use the cosine dissimilarity metric

**Comment by skn123** [comment]
I think this is coming from GKNN
'''
void GKNN::trainInner(const GMatrix& feats, const GMatrix& labs)
{
	//if(m_pSparseMetric)
	//	throw Ex("This method is not compatible with sparse similarity metrics. You should either use trainSparse instead, or use a dense dissimilarity metric.");
