### ISSUE TITLE
Memory leak in Random forests

### ISSUE THREAD

**Issue by skn123** [mikegashler/waffles#9]
All other classifiers are working fine but this.

**Comment by mikegashler** [comment]
Got a repro? My attempt found no leaks:

$ valgrind --leak-check=full waffles_learn crossvalidate iris.arff randomforest 20
==1921== Memcheck, a memory error detector
==1921== Copyright (C) 2002-2013, and GNU GPL'd, by Julian Seward et al.
==1921== Using Valgrind-3.10.1 and LibVEX; rerun with -h for copyright info
==1921== Command: waffles_learn crossvalidate iris.arff randomforest 20
==1921== 
==1921== 
==1921== HEAP SUMMARY:
==1921==     in use at exit: 0 bytes in 0 blocks
==1921==   total heap usage: 15,280 allocs, 15,280 frees, 583,122 bytes allocated
==1921== 
==1921== All heap blocks were freed -- no leaks are possible
==1921== 
==1921== For counts of detected and suppressed errors, rerun with: -v
==1921== ERROR SUMMARY: 0 errors from 0 contexts (suppressed: 0 from 0)
